/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class MakananMenu extends javax.swing.JFrame {

    /**
     * Creates new form MakananMenu
     */
    public MakananMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxbaksobiasa = new javax.swing.JCheckBox();
        cbxbaksobesar = new javax.swing.JCheckBox();
        cbxmieayam = new javax.swing.JCheckBox();
        cbxmieayambaksobiasa = new javax.swing.JCheckBox();
        cbxmieayambaksobesar = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        txtjumlah2 = new javax.swing.JTextField();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        txtjumlah5 = new javax.swing.JTextField();
        cbxesjeruk = new javax.swing.JCheckBox();
        cbxesteh = new javax.swing.JCheckBox();
        cbxjerukhangat = new javax.swing.JCheckBox();
        cbxtehhangat = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtjumlah6 = new javax.swing.JTextField();
        txtjumlah7 = new javax.swing.JTextField();
        txtjumlah8 = new javax.swing.JTextField();
        txtjumlah9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txapesan = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Makanan :");

        jLabel2.setText("Harga :");

        jLabel3.setText("Jumlah :");

        cbxbaksobiasa.setText("Bakso Biasa");
        cbxbaksobiasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxbaksobiasaActionPerformed(evt);
            }
        });

        cbxbaksobesar.setText("Bakso Besar");

        cbxmieayam.setText("Mie Ayam");

        cbxmieayambaksobiasa.setText("Mie Ayam Bakso Biasa");

        cbxmieayambaksobesar.setText("Mie Ayam Bakso Besar");

        jLabel5.setText("Menu Minuman :");

        jLabel6.setText("Harga:");

        jLabel7.setText("Jumlah :");

        jLabel8.setText("Rp.13.000");

        jLabel9.setText("Rp.18.000");

        jLabel10.setText("Rp.11.000");

        jLabel11.setText("Rp.15.000");

        jLabel13.setText("Rp.27.000");

        cbxesjeruk.setText("Es Jeruk");

        cbxesteh.setText("Es Teh");

        cbxjerukhangat.setText("Jeruk Hangat");

        cbxtehhangat.setText("Teh Hangat");

        jLabel14.setText("Rp.5.000");

        jLabel15.setText("Rp.5.000");

        jLabel16.setText("Rp.4.000");

        jLabel17.setText("Rp.4.000");

        jLabel19.setText("Menu Yang Di Pesan :");

        txapesan.setColumns(20);
        txapesan.setRows(5);
        jScrollPane1.setViewportView(txapesan);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbxbaksobiasa)
                            .addComponent(cbxbaksobesar)
                            .addComponent(cbxmieayam)
                            .addComponent(cbxmieayambaksobiasa)
                            .addComponent(cbxmieayambaksobesar)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(txtjumlah1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(txtjumlah2)
                                    .addComponent(txtjumlah3)
                                    .addComponent(txtjumlah4)
                                    .addComponent(txtjumlah5))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbxesjeruk)
                                    .addComponent(cbxesteh)
                                    .addComponent(cbxjerukhangat)
                                    .addComponent(cbxtehhangat))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(txtjumlah7, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(txtjumlah8)
                                    .addComponent(txtjumlah9)
                                    .addComponent(txtjumlah6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btnpesan)
                        .addGap(200, 200, 200)
                        .addComponent(btnreset)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxbaksobiasa)
                    .addComponent(jLabel8)
                    .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxesjeruk)
                    .addComponent(jLabel14)
                    .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxbaksobesar)
                    .addComponent(jLabel9)
                    .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxesteh)
                    .addComponent(jLabel15)
                    .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxmieayam)
                    .addComponent(jLabel10)
                    .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxjerukhangat)
                    .addComponent(jLabel16)
                    .addComponent(txtjumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxmieayambaksobiasa)
                    .addComponent(jLabel11)
                    .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxtehhangat)
                    .addComponent(jLabel17)
                    .addComponent(txtjumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxmieayambaksobesar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpesan)
                    .addComponent(btnreset))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if (cbxbaksobiasa.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*13000;
            bayar=bayar+total;
            tampil+=cbxbaksobiasa.getText()+" Rp.13000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxbaksobesar.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*18000;
            bayar=bayar+total;
            tampil+=cbxbaksobesar.getText()+" Rp.18000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxmieayam.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*11000;
            bayar=bayar+total;
            tampil+=cbxmieayam.getText()+" Rp.11000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxmieayambaksobiasa.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil+=cbxmieayambaksobiasa.getText()+" Rp.15000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxmieayambaksobesar.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*27000;
            bayar=bayar+total;
            tampil+=cbxmieayambaksobesar.getText()+" Rp.27000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxesjeruk.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxesjeruk.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxesteh.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxesteh.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxjerukhangat.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*4000;
            bayar=bayar+total;
            tampil+=cbxjerukhangat.getText()+" Rp.4000"+" x "+jumlah+" = "+total+"\n";
        }if (cbxtehhangat.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah9.getText());
            int total;
            total=jumlah*4000;
            bayar=bayar+total;
            tampil+=cbxtehhangat.getText()+" Rp.4000"+" x "+jumlah+" = "+total+"\n";
        }
        txapesan.setText(tampil+"=========================="+"\n"+"Total Bayar ="+bayar);
    }//GEN-LAST:event_btnpesanActionPerformed

    private void cbxbaksobiasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxbaksobiasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxbaksobiasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakananMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakananMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxbaksobesar;
    private javax.swing.JCheckBox cbxbaksobiasa;
    private javax.swing.JCheckBox cbxesjeruk;
    private javax.swing.JCheckBox cbxesteh;
    private javax.swing.JCheckBox cbxjerukhangat;
    private javax.swing.JCheckBox cbxmieayam;
    private javax.swing.JCheckBox cbxmieayambaksobesar;
    private javax.swing.JCheckBox cbxmieayambaksobiasa;
    private javax.swing.JCheckBox cbxtehhangat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txapesan;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtjumlah9;
    // End of variables declaration//GEN-END:variables
}
